repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run isort.
    - id: ruff-check
      types_or: [ python, pyi, jupyter]
      args: [ --select, I, --fix ]
    # Run the formatter.
    - id: ruff-format
      # args: [--diff]
      types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
    - id: insert-license
      types: [ python ]
      args:
        - --use-current-year
        - --license-filepath
        - doc/license_header.txt
