version: "2"

build:
  os: "ubuntu-lts-latest"
  apt_packages:
    - pandoc
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  configuration: doc/conf.py